# fly.toml app configuration file generated for substackgraph-jm6dyg on 2026-06-06T02:21:20Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'substackgraph-jm6dyg'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  ALLOW_LIVE_CRAWL = '0'
  SEED_URL = 'https://theairuntime.substack.com'
  SUBSTACKGRAPH_DB = '/data/cache.sqlite'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/healthz'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
